"""Compatibility constants published by the Control Plane version endpoint."""

from typing import Final

API_VERSION: Final = "v1"
CURRENT_DESKTOP_APP_VERSION: Final = "0.1.0"
MINIMUM_COMPATIBLE_DESKTOP_APP_VERSION: Final = "0.1.0"
MAXIMUM_COMPATIBLE_DESKTOP_APP_VERSION: Final = "0.1.0"
CURRENT_EXECUTOR_RUNTIME_VERSION: Final = "0.1.0"
MINIMUM_COMPATIBLE_EXECUTOR_RUNTIME_VERSION: Final = "0.1.0"
MAXIMUM_COMPATIBLE_EXECUTOR_RUNTIME_VERSION: Final = "0.1.0"
CURRENT_EXECUTOR_PROTOCOL: Final = "1.0"
EXECUTOR_WEBSOCKET_SUBPROTOCOL: Final = "automation-tool.executor.v1"
MINIMUM_COMPATIBLE_EXECUTOR_PROTOCOL: Final = "1.0"
MAXIMUM_COMPATIBLE_EXECUTOR_PROTOCOL: Final = "1.0"
