"""Control Plane domain contracts and errors."""

from automation_tool.control_plane.domain.accounts import (
    MAX_PASSWORD_CHARACTERS,
    MIN_PASSWORD_CHARACTERS,
    AccountAuditActorKind,
    AccountAuditEventType,
    AccountStatus,
    InvalidAccountModel,
    LoginName,
    PasswordHash,
)
from automation_tool.control_plane.domain.action_risk_policy import (
    ACTION_RISK_POLICY_VERSION,
    MAX_ACTION_RISK_LIMIT,
    ActionRiskPlatform,
    ActionRiskPolicy,
    ActionRiskScope,
    InvalidActionRiskPolicy,
)
from automation_tool.control_plane.domain.demo_bootstrap import (
    MAX_DEMO_BOOTSTRAP_LIFETIME,
    BootstrapAuthorizationDenied,
    BootstrapDenialReason,
    BootstrapPurpose,
    DemoBootstrapGrant,
    DemoEnvironmentId,
    InvalidDemoBootstrap,
    InvalidDemoEnvironmentId,
)
from automation_tool.control_plane.domain.douyin_candidate_policy import (
    DOUYIN_CANDIDATE_HISTORY_WINDOW,
    DOUYIN_CANDIDATE_POLICY_VERSION,
    DouyinCandidateDecision,
    DouyinCandidateDisposition,
    DouyinCandidateEvaluation,
    DouyinCandidateHistoryFact,
    InvalidDouyinCandidatePolicy,
    evaluate_douyin_candidates,
)
from automation_tool.control_plane.domain.errors import DependencyUnavailable
from automation_tool.control_plane.domain.execution_models import (
    TERMINAL_ACTION_STATUSES,
    TERMINAL_EXECUTION_ATTEMPT_STATUSES,
    ActionOutcome,
    ActionStatus,
    ExecutionAttemptStatus,
)
from automation_tool.control_plane.domain.installations import InstallationStatus
from automation_tool.control_plane.domain.ports import DatabaseLifecycle
from automation_tool.control_plane.domain.resource_ids import (
    ActionId,
    ArtifactId,
    ExecutionAttemptId,
    ExecutorConnectionId,
    ExecutorId,
    InstallationId,
    InvalidResourceId,
    ResourceId,
    TargetId,
    TaskId,
    UserId,
)
from automation_tool.control_plane.domain.task_commands import (
    TERMINAL_TASK_COMMAND_STATUSES,
    TaskCommandResponseType,
    TaskCommandStatus,
    TaskCommandType,
)
from automation_tool.control_plane.domain.task_definitions import (
    DOUYIN_SEARCH_EXPOSURE_TEMPLATE,
    MAX_MESSAGE_TEMPLATE_CHARACTERS,
    MAX_SEARCH_KEYWORD_CHARACTERS,
    MAX_TASK_INTERVAL_SECONDS,
    MAX_TASK_TARGET_LIMIT,
    DouyinSearchExposureAction,
    DouyinSearchExposureDefinition,
    InvalidTaskDefinition,
)
from automation_tool.control_plane.domain.task_events import (
    MAX_SAFE_TASK_EVENT_MESSAGE_CHARACTERS,
    MAX_TASK_EVENT_SEQUENCE,
    InvalidTaskEventModel,
    SafeTaskEventMessage,
    TaskEventType,
    TaskEventVersion,
    TaskSnapshotProjection,
)
from automation_tool.control_plane.domain.task_state_machine import (
    InvalidTaskTransition,
    TaskStateMachine,
    TaskStatus,
)

__all__ = [
    "ACTION_RISK_POLICY_VERSION",
    "DOUYIN_CANDIDATE_HISTORY_WINDOW",
    "DOUYIN_CANDIDATE_POLICY_VERSION",
    "DOUYIN_SEARCH_EXPOSURE_TEMPLATE",
    "MAX_ACTION_RISK_LIMIT",
    "MAX_DEMO_BOOTSTRAP_LIFETIME",
    "MAX_MESSAGE_TEMPLATE_CHARACTERS",
    "MAX_PASSWORD_CHARACTERS",
    "MAX_SAFE_TASK_EVENT_MESSAGE_CHARACTERS",
    "MAX_SEARCH_KEYWORD_CHARACTERS",
    "MAX_TASK_EVENT_SEQUENCE",
    "MAX_TASK_INTERVAL_SECONDS",
    "MAX_TASK_TARGET_LIMIT",
    "MIN_PASSWORD_CHARACTERS",
    "TERMINAL_ACTION_STATUSES",
    "TERMINAL_EXECUTION_ATTEMPT_STATUSES",
    "TERMINAL_TASK_COMMAND_STATUSES",
    "AccountAuditActorKind",
    "AccountAuditEventType",
    "AccountStatus",
    "ActionId",
    "ActionOutcome",
    "ActionRiskPlatform",
    "ActionRiskPolicy",
    "ActionRiskScope",
    "ActionStatus",
    "ArtifactId",
    "BootstrapAuthorizationDenied",
    "BootstrapDenialReason",
    "BootstrapPurpose",
    "DatabaseLifecycle",
    "DemoBootstrapGrant",
    "DemoEnvironmentId",
    "DependencyUnavailable",
    "DouyinCandidateDecision",
    "DouyinCandidateDisposition",
    "DouyinCandidateEvaluation",
    "DouyinCandidateHistoryFact",
    "DouyinSearchExposureAction",
    "DouyinSearchExposureDefinition",
    "ExecutionAttemptId",
    "ExecutionAttemptStatus",
    "ExecutorConnectionId",
    "ExecutorId",
    "InstallationId",
    "InstallationStatus",
    "InvalidAccountModel",
    "InvalidActionRiskPolicy",
    "InvalidDemoBootstrap",
    "InvalidDemoEnvironmentId",
    "InvalidDouyinCandidatePolicy",
    "InvalidResourceId",
    "InvalidTaskDefinition",
    "InvalidTaskEventModel",
    "InvalidTaskTransition",
    "LoginName",
    "PasswordHash",
    "ResourceId",
    "SafeTaskEventMessage",
    "TargetId",
    "TaskCommandResponseType",
    "TaskCommandStatus",
    "TaskCommandType",
    "TaskEventType",
    "TaskEventVersion",
    "TaskId",
    "TaskSnapshotProjection",
    "TaskStateMachine",
    "TaskStatus",
    "UserId",
    "evaluate_douyin_candidates",
]
