"""Control Plane domain contracts and errors.

Public names remain available from this package, while leaf modules are loaded
only when requested.  The local video Worker can therefore embed the editing
domain without importing unrelated platform integrations.
"""

from importlib import import_module
from typing import Any

_PUBLIC_MODULES = (
    "accounts",
    "action_risk_policy",
    "bilibili_open_api",
    "demo_bootstrap",
    "douyin_candidate_policy",
    "editing_job",
    "editing_project",
    "errors",
    "execution_models",
    "installations",
    "material",
    "ports",
    "resource_ids",
    "task_commands",
    "task_definitions",
    "task_events",
    "task_state_machine",
    "timeline",
    "video_creation",
    "video_publishing",
)


def __getattr__(name: str) -> Any:
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    for module_name in _PUBLIC_MODULES:
        module = import_module(f"{__name__}.{module_name}")
        if name in vars(module):
            value = vars(module)[name]
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "ACTION_RISK_POLICY_VERSION",
    "AUDIBLE_TRACK_KINDS",
    "BILIBILI_OPEN_API_CONTRACT_VERSION",
    "DOUYIN_CANDIDATE_HISTORY_WINDOW",
    "DOUYIN_CANDIDATE_POLICY_VERSION",
    "DOUYIN_SEARCH_EXPOSURE_TEMPLATE",
    "FIRST_RELEASE_PUBLISHING_CAPABILITIES",
    "MAX_ACTION_RISK_LIMIT",
    "MAX_CAPTION_FONT_PX",
    "MAX_CAPTION_LINE_SPACING",
    "MAX_CAPTION_STROKE_PX",
    "MAX_DEMO_BOOTSTRAP_LIFETIME",
    "MAX_DESCRIPTION_CHARACTERS",
    "MAX_MATERIAL_DIMENSION",
    "MAX_MATERIAL_DURATION_MS",
    "MAX_MESSAGE_TEMPLATE_CHARACTERS",
    "MAX_OUTPUT_DIMENSION",
    "MAX_OUTPUT_FPS",
    "MAX_PASSWORD_CHARACTERS",
    "MAX_PROJECT_TITLE_CHARACTERS",
    "MAX_SAFE_TASK_EVENT_MESSAGE_CHARACTERS",
    "MAX_SEARCH_KEYWORD_CHARACTERS",
    "MAX_SHOT_BOUNDARIES",
    "MAX_SPEECH_SEGMENTS",
    "MAX_TAGS",
    "MAX_TAG_CHARACTERS",
    "MAX_TASK_EVENT_SEQUENCE",
    "MAX_TASK_INTERVAL_SECONDS",
    "MAX_TASK_TARGET_LIMIT",
    "MAX_TRANSCRIPT_CHARACTERS",
    "MIN_CAPTION_FONT_PX",
    "MIN_CAPTION_LINE_SPACING",
    "MIN_OUTPUT_DIMENSION",
    "MIN_OUTPUT_FPS",
    "MIN_PASSWORD_CHARACTERS",
    "PUBLISHING_CAPABILITIES_CONTRACT_VERSION",
    "TERMINAL_ACTION_STATUSES",
    "TERMINAL_EXECUTION_ATTEMPT_STATUSES",
    "TERMINAL_TASK_COMMAND_STATUSES",
    "AccountAuditActorKind",
    "AccountAuditEventType",
    "AccountStatus",
    "ActionId",
    "ActionOutcome",
    "ActionRiskPlatform",
    "ActionRiskPolicy",
    "ActionRiskScope",
    "ActionStatus",
    "ArchiveListPage",
    "ArchiveStatusNotification",
    "ArchiveStatusSnapshot",
    "ArchiveSubmissionReceipt",
    "Artifact",
    "ArtifactId",
    "ArtifactRole",
    "BilibiliErrorCategory",
    "BilibiliOpenApiContract",
    "BilibiliPlatformRejection",
    "BootstrapAuthorizationDenied",
    "BootstrapDenialReason",
    "BootstrapPurpose",
    "CaptionStyle",
    "ContentBrief",
    "ContentBriefId",
    "CoverUploadResult",
    "DatabaseLifecycle",
    "DemoBootstrapGrant",
    "DemoEnvironmentId",
    "DependencyUnavailable",
    "DescriptionSource",
    "DouyinCandidateDecision",
    "DouyinCandidateDisposition",
    "DouyinCandidateEvaluation",
    "DouyinCandidateHistoryFact",
    "DouyinSearchExposureAction",
    "DouyinSearchExposureDefinition",
    "EditingJob",
    "EditingJobFailureCode",
    "EditingJobId",
    "EditingJobStateMachine",
    "EditingJobStatus",
    "EditingProject",
    "EditingProjectId",
    "ExecutionAttemptId",
    "ExecutionAttemptStatus",
    "ExecutorConnectionId",
    "ExecutorId",
    "InstallationId",
    "InstallationStatus",
    "InvalidAccountModel",
    "InvalidActionRiskPolicy",
    "InvalidBilibiliOpenApiContract",
    "InvalidBilibiliOpenApiMessage",
    "InvalidDemoBootstrap",
    "InvalidDemoEnvironmentId",
    "InvalidDouyinCandidatePolicy",
    "InvalidEditingJobModel",
    "InvalidEditingJobTransition",
    "InvalidEditingProjectModel",
    "InvalidMaterialModel",
    "InvalidPublishJobTransition",
    "InvalidResourceId",
    "InvalidTaskDefinition",
    "InvalidTaskEventModel",
    "InvalidTaskTransition",
    "InvalidTimelineModel",
    "InvalidVideoDomainModel",
    "InvalidVideoPublishingModel",
    "LoginName",
    "Material",
    "MaterialId",
    "MaterialKind",
    "OriginalAudioMode",
    "OutputSpec",
    "PasswordHash",
    "PublishCapability",
    "PublishFailureCode",
    "PublishJob",
    "PublishJobId",
    "PublishJobStateMachine",
    "PublishJobStatus",
    "PublishMechanism",
    "PublishPlatform",
    "RenderFailureCode",
    "RenderJob",
    "RenderJobId",
    "RenderJobStatus",
    "ResourceId",
    "SafeTaskEventMessage",
    "Storyboard",
    "StoryboardId",
    "StoryboardScene",
    "TargetId",
    "TaskCommandResponseType",
    "TaskCommandStatus",
    "TaskCommandType",
    "TaskEventType",
    "TaskEventVersion",
    "TaskId",
    "TaskSnapshotProjection",
    "TaskStateMachine",
    "TaskStatus",
    "Timeline",
    "TimelineClip",
    "TimelineId",
    "TimelineTrack",
    "TimelineTrackKind",
    "TimelineTransition",
    "TokenGrant",
    "TokenRefresh",
    "TransitionKind",
    "UploadSession",
    "UserId",
    "VideoAspectRatio",
    "VideoCreationMethod",
    "classify_error_code",
    "compute_webhook_signature",
    "enabled_publish_platforms",
    "evaluate_douyin_candidates",
    "load_bilibili_open_api_contract",
    "parse_archive_add",
    "parse_archive_status_notification",
    "parse_archive_view",
    "parse_archive_viewlist",
    "parse_cover_upload",
    "parse_token_grant",
    "parse_token_refresh",
    "parse_transfer_ack",
    "parse_upload_init",
    "parse_webhook_verification",
    "plan_upload_parts",
    "publish_capability_for",
    "validate_archive_submission",
    "validate_part_number",
    "validate_upload_init_request",
    "verify_webhook_signature",
]
